export const websettingInputFieldData = [
  {
    label: "Title",
    name: "title",
    type: "text",
    placeholder: "Enter Title",
    rules: "Title is required",
  },
  {
    label: "Email",
    name: "email",
    type: "email",
    placeholder: "Enter Email",
    rules: "Email is required",
  },
  {
    label: "Phone",
    name: "phone",
    type: "text",
    placeholder: "Enter Phone",
    rules: "Phone is required",
  },
  {
    label: "Bio",
    name: "bio",
    type: "text",
    placeholder: "Enter Bio",
    rules: "Bio is required",
  },
  {
    label: "Location",
    name: "location",
    type: "text",
    placeholder: "Enter Location",
    rules: "Location is required",
  },
  {
    label: "Linkedin",
    name: "linkedin",
    type: "text",
    placeholder: "Enter Linkedin Url",
    rules: "",
  },
  {
    label: "Instagram",
    name: "instagram",
    type: "text",
    placeholder: "Enter Instagram URL",
    rules: "",
  },
  {
    label: "Facebook",
    name: "facebook",
    type: "text",
    placeholder: "Enter Facebook URL",
    rules: "",
  },
  {
    label: "Youtube",
    name: "youtube",
    type: "text",
    placeholder: "Enter Youtube URL",
    rules: "",
  },
  {
    label: "Twitter",
    name: "twitter",
    type: "text",
    placeholder: "Enter Twitter Url",
    rules: "",
  },
  {
    label: "Logo",
    name: "logo",
    type: "file",
    placeholder: "Enter Logo",
    rules: "Logo must be uploaded",
  },
];
